# Generated by Django 4.0.4 on 2022-07-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweek',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
