# Generated by Django 4.0.4 on 2022-07-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_programday'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatcollection',
            name='program_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.programday'),
        ),
        migrations.AddField(
            model_name='dailystatcollection',
            name='weekday',
            field=models.IntegerField(null=True),
        ),
    ]
