# Generated by Django 4.0.4 on 2022-07-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentweek_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatcollection',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
