# Generated by Django 4.0.4 on 2022-07-14 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_dailystatcollection_program_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programday',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
