# Generated by Django 4.0.4 on 2022-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_dailystatcollection_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatcollection',
            name='did_check_in_before_noon',
            field=models.BooleanField(default=False),
        ),
    ]
