# Generated by Django 4.0.4 on 2022-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_dailystatcollection_did_check_in_before_noon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='subject',
            field=models.CharField(default='english', max_length=20),
        ),
    ]
