# Generated by Django 4.0.4 on 2022-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_programday_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatcollection',
            name='weekday',
        ),
        migrations.AddField(
            model_name='dailystatcollection',
            name='work_day',
            field=models.IntegerField(null=True),
        ),
    ]
