# Generated by Django 4.0.4 on 2022-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_dailystatcollection_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatcollection',
            name='date',
            field=models.DateField(),
        ),
    ]
